/** mddl.h - mddl stubs and snippets */

#if !defined INCLUDED_mddl_h_
#define INCLUDED_mddl_h_

#undef DECLF
#undef DEFUN
#if defined STATIC_GUTS
# define DEFUN	static
# define DECLF	static
#else  /* !STATIC_GUTS */
# define DEFUN
# define DECLF	extern
#endif	/* STATIC_GUTS */

typedef struct __mddl_s *mddl_doc_t;

typedef char *mddl_ID_t;
typedef char *mddl_mdString_t;
typedef char *mddl_string_t;
typedef char *mddl_mdUri_t;
typedef char *mddl_anyURI_t;

typedef double xsd_decimal_t;
typedef xsd_decimal_t mddl_mdDecimal_t;
typedef xsd_decimal_t mddl_mdNonNegativeDecimal_t;

typedef int mddl_mdBoolean_t;
typedef long int xsd_integer_t;
typedef xsd_integer_t mddl_mdInteger_t;

typedef union AnyDateTime_u mddl_AnyDateTime_t;
typedef time_t mddl_mdDateTime_t;
typedef time_t mddl_mdDuration_t;

typedef time_t xsd_dateTime_t;
typedef time_t xsd_date_t;
typedef time_t xsd_time_t;

typedef enum {
	QE_UNK,
	QE_VALID,
	QE_UNAVAILABLE,
} mddl_QualityEnumeration_t;

/* autogenerated files */
#include "mddl-3.0-beta-spec.h"
#include "mddl-3.0-beta-funs.h"

/* print service */
DECLF void mddl_print(void *out, mddl_doc_t doc);

#endif	/* INCLUDED_mddl_h_ */
